"""payment_type for order

Revision ID: 0856748e0d17
Revises: 924affc29890
Create Date: 2024-09-05 10:38:04.801398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from global_constants import PaymentType

# revision identifiers, used by Alembic.
revision: str = '0856748e0d17'
down_revision: Union[str, None] = '924affc29890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column(
            'payment_type',
            sqlalchemy_utils.types.choice.ChoiceType(
                choices=PaymentType,
                impl=sa.String(length=16)
            ),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_type')
    # ### end Alembic commands ###
