"""change products fields

Revision ID: 090099c8013e
Revises: c8f4f1d6796a
Create Date: 2024-08-19 16:23:53.355967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090099c8013e'
down_revision: Union[str, None] = 'c8f4f1d6796a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.add_column('products', sa.Column('description', sa.String(length=1024), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_image', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('catalog_image', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    # ### end Alembic commands ###
