"""added_payment_status

Revision ID: 5e9fb92795c0
Revises: 92ef22dc8215
Create Date: 2024-08-29 17:14:13.517396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from global_constants import PaymentStatus


# revision identifiers, used by Alembic.
revision: str = '5e9fb92795c0'
down_revision: Union[str, None] = '92ef22dc8215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('payment_status', sqlalchemy_utils.types.choice.ChoiceType(choices=PaymentStatus, impl=sa.String(length=32)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'payment_status')
    # ### end Alembic commands ###
