"""orders

Revision ID: 924affc29890
Revises: 88d2a229a884
Create Date: 2024-09-02 16:33:18.663443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924affc29890'
down_revision: Union[str, None] = '88d2a229a884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('street', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('house_number', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('apartment', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'apartment')
    op.drop_column('orders', 'house_number')
    op.drop_column('orders', 'street')
    op.drop_column('orders', 'city')
    # ### end Alembic commands ###
