"""created_at for order

Revision ID: f3d1402528a5
Revises: 0856748e0d17
Create Date: 2024-09-05 16:23:47.569623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from global_constants import DeliveryType

# revision identifiers, used by Alembic.
revision: str = 'f3d1402528a5'
down_revision: Union[str, None] = '0856748e0d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(
        'orders',
        sa.Column(
            'delivery_type',
            sqlalchemy_utils.types.choice.ChoiceType(choices=DeliveryType, impl=sa.String(length=16)),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_type')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
